### ISSUE TITLE
So slow for 5000 objects. 

### ISSUE THREAD

**Issue by kopaygorodsky** [theofidry/AliceDataFixtures#48] opened 2017-09-05 01:20 UTC
I have a set of fixtures with sum  ~ 5000 objects. Bundle takes a few minutes to process them. 
Cycle  `while(true) ` in MultiPassLoader.php requires 90 sec for 11 files. 
It's 90 seconds only to create objects, without persisting them to db. 
How it can be improved? 
I'm using Mac Pro, php 7.1

**Comment by theofidry** [comment] 2017-09-05 07:37
I have no idea how to improve it, the first step would be to profile it :)

90sec for 5K is definitely slow, usually slowness comes from:

- Very very very high fixture complexity with a lot of deep relationships (unlikely)
- Poor data availability combined with `unique`: if you require 90 unique values and there is only 90 of them available, it will take time.

In any case, a Blackfire profile is mandatory to be able to see what the issue is

**Comment by kopaygorodsky** [comment] 2017-09-05 12:06
@theofidry I don't have complex relations, 2-4 links, also don't have  any unique values. 
I will try to investigate where is the problem, fix it and commit.

**Comment by theofidry** [comment] 2017-09-05 17:06
It sounds very weird then. A Blackfire profile is the way to go 😄

**Comment by theofidry** [comment] 2017-09-14 21:19
Did you find anything @kopaygorodsky?

**Comment by kopaygorodsky** [comment] 2017-09-17 21:00
@theofidry sry, I had a weekend, will take a look tomorrow :)

**Comment by kopaygorodsky** [comment] 2017-09-18 19:29
https://github.com/hautelook/AliceBundle/issues/139

**Comment by theofidry** [comment] 2017-09-18 19:52
Well that's not really helping :)

That issue has been closed due lack of elements. Without a concrete case we can test, debug or profile, it's hard to tell what the bottleneck is and what can be done.

**Comment by kopaygorodsky** [comment] 2017-09-18 20:04
@theofidry I'm testing it right now.  Got through all channel from console command to DoublePassGenerator. 
generate for file with 1k of objects takes 15 sec (ok), file with 3k (3 entities* 1k per entity) 120 sec.

**Comment by theofidry** [comment] 2017-09-18 20:16
Ok, link me the profile once you have it then. There's a benchmark on alice, I just checked it and I can confirm it usually goes between 4-20sec for 4K objects. While not being most impressive, I think that's ok for what it does and there is always https://github.com/nelmio/alice/pull/651 that could be worked on otherwise.

**Comment by kopaygorodsky** [comment] 2017-09-19 14:32
https://blackfire.io/profiles/48d7dbec-2064-4fe0-8998-d95ff9111f3e/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()

**Comment by theofidry** [comment] 2017-09-19 14:38
are you sure it's the right graph? It took less than 3sec and I can't see any call done from alice

**Comment by theofidry** [comment] 2017-09-19 14:39
to run a blackfire from the CLI you can do `blackfire run -i 'php bin/console ...'

**Comment by theofidry** [comment] 2017-09-19 15:09
Looks like the two bottlenecks are:

- deep cloning (we could try to limit its usage in alice but it's tricky)
- make the deep cloning faster (tricky as well but doable)

Another big bottleneck you can try to get rid of is the garbage collection, you can do so by doing `php -d zend.enable_gc=0 <your command here>`

**Comment by kopaygorodsky** [comment] 2017-09-19 22:42
I know, thank you. It's a trade-off memory/time. Will take a look on deep cloning.

**Comment by theofidry** [comment] 2017-10-01 13:18
Closing as there is not much more than can be done for now. IMO the first thing that can be done is disabling xdebug (alice has a lot of recursive code, xdebug is much worse than usual for anything recursive), garbage collection (it's unlikely to jump more than 100MB so you don't need a supercomputer for it).

Two other solutions would be to find a way to make the deep-cloning faster (it would be interesting to see the slow parts, maybe just declaring custom `__clone()` method would be enough) and implement a cache (see. nelmio/alice#651)

**Closed by theofidry** 2017-10-01 13:18 UTC

**Comment by romainnorberg** [comment] 2018-11-22 10:00
solution with `php -d zend.enable_gc=0 <your command here>` save me a lot of time. From ~3min to ~10sec 🚀 

Thanks @theofidry
