### ISSUE TITLE
Is it possible to set the order of clearing tables in the database?

### ISSUE THREAD

**Issue by nickicool** [theofidry/AliceDataFixtures#171] opened 2021-04-17 20:00 UTC
Hi!

Adding fixtures is performed without problems - the script itself determines the structure of dependencies, and adds the necessary entities in the right order. It is a magic!!!

But the purging database doesn't go so well. Depending on the existing data in database, sometimes I got errors like:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (
  `vita-master`.`pricelists`, CONSTRAINT `FK_28511D04C4663E4` FOREIGN KEY (`page_id`) REFERENCES `pages` (`id`))

Is it possible to set the order of clearing tables in the database?

**Comment by theofidry** [comment] 2021-05-11 06:30
This is curious because the FK checks should be disabled while purging: https://github.com/theofidry/AliceDataFixtures/blob/master/src/Bridge/Doctrine/Purger/Purger.php#L98

**Comment by chasovskih-grisha** [comment] 2021-06-21 11:31
the same issue...

**Comment by theofidry** [comment] 2021-09-26 19:43
Sorry I cannot help without reproducers. But otherwise no there is no way, the purgers are directly from https://github.com/doctrine/DoctrineFixturesBundle

**Comment by theofidry** [comment] 2021-12-21 12:13
I suspect this is fixed by #194

**Closed by theofidry** 2021-12-21 12:13 UTC
