### ISSUE TITLE
OrmPurger not found

### ISSUE THREAD

**Issue by versh23** [theofidry/AliceDataFixtures#44] opened 2017-07-01 06:58 UTC
Hello!
after upgrade to v1.0.0-beta.5 i get an error

```
06:50:29 ERROR     [console] Error thrown while running command "hautelook:fixtures:load --no-interaction --env=dev".
Message: "Class 'Fidry\AliceDataFixtures\Bridge\Doctrine\Purger\OrmPurger' not found" ["error" => Error {trace: { …} …
},"command" => "hautelook:fixtures:load --no-interaction --env=dev","message" => "Class 'Fidry\AliceDataFixtures\Bridg
e\Doctrine\Purger\OrmPurger' not found"] []
```
downgrade to beta4 solve the problem.

I use symfony 3.3.2 and php 7.1

#42

**Comment by theofidry** [comment] 2017-07-01 07:24
Duplicate of https://github.com/hautelook/AliceBundle/issues/346, there is https://github.com/hautelook/AliceBundle/pull/345 which fixes that but the build is not green yet (hence it's not merged yet)

**Closed by theofidry** 2017-07-01 07:24 UTC
